name: Bug report
description: Report a problem with Ef themes
labels: [bug]
body:
  - type: textarea
    attributes:
      label: "Description"
      description: "A short description of the problem you are reporting."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Neovim version"
      description: "Output of `nvim --version` (Ef themes requires neovim >= 0.8)"
      render: markdown
      placeholder: |
        NVIM v0.9.4
        Build type: Release
        LuaJIT 2.1.1692716794
    validations:
      required: true
  - type: input
    attributes:
      label: "Terminal and multiplexer"
      placeholder: "kitty 0.29.2 with tmux 3.3a"
  - type: input
    attributes:
      label: "Ef themes version"
      placeholder: "ef-themes.nvim v1.0.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Steps to reproduce using the minimal config provided below."
      placeholder: |
        1. `nvim -u repro.lua`
        2. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Repro
      description:
        Minimal `init.lua` to reproduce this issue. Save as `repro.lua` and run with
        `nvim -u repro.lua`
      value: |
        -- DO NOT change the paths and don't remove the colorscheme
        local root = vim.fn.fnamemodify("./.repro", ":p")

        -- set stdpaths to use .repro
        for _, name in ipairs({ "config", "data", "state", "cache" }) do
          vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
        end

        -- bootstrap lazy
        local lazypath = root .. "/plugins/lazy.nvim"
        if not vim.loop.fs_stat(lazypath) then
          vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
        end
        vim.opt.runtimepath:prepend(lazypath)

        -- install plugins
        local plugins = {
          "theopechli/ef-themes.nvim",
          -- add any other plugins here
        }
        require("lazy").setup(plugins, {
          root = root .. "/plugins",
        })

        vim.cmd.colorscheme("ef")
        -- add anything else here
      render: Lua
